version: "3"
services:

  redaxo:
    image: friendsofredaxo/redaxo:5
    ports:
      - 20080:80                            # web server will use port 20080
    volumes:
      - ./app:/var/www/html:cached          # sync webroot with local folder `app`
    depends_on:
      - db                                  # requires database container to be available

  db:
    image: mysql:5
    volumes:
      - ./db:/var/lib/mysql:cached          # sync database with local folder `db`
    environment:
      MYSQL_DATABASE: redaxo
      MYSQL_USER: redaxo
      MYSQL_PASSWORD: redaxo
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
